spring:
  application:
    name: video-download-service

server:
  port: ${SERVER_PORT:8085}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

app:
  storage:
    type: ${APP_STORAGE_TYPE:local}
    local:
      processed-path: ${STORAGE_OUTPUT_PATH:/app/videos/processed}
  presign:
    ttl-minutes: ${PRESIGN_TTL_MINUTES:15}

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8090}

logging:
  level:
    br.com.fiap: INFO
    org.springframework: WARN

---
spring:
  config:
    activate:
      on-profile: test

app:
  storage:
    type: local-test

---
spring:
  config:
    activate:
      on-profile: docker

app:
  storage:
    type: local
