version: '3.8'
name: ms-video-download

services:
  video-download-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-download-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8085
      APP_STORAGE_TYPE: local
      STORAGE_OUTPUT_PATH: /app/videos/processed
      PRESIGN_TTL_MINUTES: 15
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth-api:8090}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      NEW_RELIC_APP_NAME: video-download-ms-local
    ports:
      - "8085:8085"
    volumes:
      - ./videos/processed:/app/videos/processed
    networks:
      - app-network
      - fiap-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  fiap-network:
    external: true
    name: fiap-network
